#! /bin/bash

# Set up symlinks
ln -nfs "$(pwd)/.gemrc"            "$HOME/.gemrc"
ln -nfs "$(pwd)/.irbrc"            "$HOME/.irbrc"
ln -nfs "$(pwd)/zsh/.zshrc"             "$HOME/.zshrc"
ln -nfs "$(pwd)/zsh/.zsh"               "$HOME/.zsh"
ln -nfs "$(pwd)/.ruby-version"          "$HOME/.ruby-version"
ln -nfs "$(pwd)/hammerspoon"            "$HOME/.hammerspoon"
ln -nfs "$(pwd)/.gitignore_global"  "$HOME/.gitignore_global"

# Copy powerlines
for file in ./powerline-fonts/Meslo/*.otf; do
  cp -f "$file" "$HOME/Library/Fonts/"
done

git config --global user.email "gabrielglescinskas@gmail.com"
git config --global user.name "Gabriel G. Lescinskas"
git config --global core.excludesfile "$HOME/.gitignore_global"
git config --global color.diff always
git config --global merge.ff only
git config --global push.default current
git config --global remote.origin.prune true
git config --global rebase.autosquash true
